name: Build iOS
on: workflow_dispatch


jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "Setup JAVA"
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: "stable"  
      - name: "Install Flutter dependencies"
        run: flutter pub get
      - name: "Clean the project"
        run: flutter clean
      - name: "iOS Build"
        run: flutter build ios