name: CI
on:
  pull_request:
    branches:
      - main
  
jobs:
  flutter_test_analyze:
    name: Run flutter test, analyze
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "Setup JAVA"
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: "Install Flutter dependencies"
        run: flutter pub get
      - name: "🔬 Analyze files"
        run: flutter analyze
      - name: "🧪 Run the tests"
        run: flutter test